### ISSUE TITLE
[Bug] Non ASCII character in Game Name break script

### ISSUE THREAD

**Issue by Qowy** [redromnon/HeroicBashLauncher#61] opened 2022-05-13 20:25 UTC
I just fixed this issue with HeroicLauncher itself, now that I managed to install the game this launcher throws the same error ;)

see https://github.com/Heroic-Games-Launcher/heroic-gogdl/issues/6

```
Using HeroicBashLauncher Flatpak version...

(process:117431): Gtk-WARNING **: 22:22:22.955: Locale not supported by C library.
	Using the fallback 'C' locale.
3.32.0
Traceback (most recent call last):
  File "HeroicBashLauncher.py", line 23, in <module>
  File "listinstalled.py", line 67, in listinstalled
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 2: ordinal not in range(128)
[117430] Failed to execute script 'HeroicBashLauncher' due to unhandled exception!
Using Bash Launcher 2.5.0
```

**Comment by redromnon** [comment] 2022-05-14 00:53
A workaround has been suggested in #57. I'll be closing this issue since it's a duplicate of that. Feel free to join the discussion there.

**Comment by Qowy** [comment] 2022-05-14 07:59
Not sure if it is a Duplicate, the other one is for the generated Game scripts. But this here crashes during listing the installed games while creating the scripts in the first place, so the proposed solution would not work?

**Comment by redromnon** [comment] 2022-05-14 10:16
Thanks for reminding me. I read the gogdl link you included, not the log you attached here, and thus tagged this as Duplicate. Both of them are quite similar and #57 also suffers from non-ascii characters when executing terminal commands. 

Actually here, the game's name contains the letter ü and is thus causing issues. Moreover, the fix that you suggested won't work here since here the program is just displaying the game's name and executing any command.

**Comment by redromnon** [comment] 2022-05-14 10:19
Maybe you can try adding implementing the workaround mentioned in #57

**Comment by redromnon** [comment] 2022-05-21 00:49
I've fixed this issue.

**Closed by redromnon** 2022-05-21 00:49 UTC
Labels: bug
