### ISSUE TITLE
[Bug] Cannot log in on HeroicBashLauncher

### ISSUE THREAD

**Issue by redirectto** [redromnon/HeroicBashLauncher#130] opened 2023-08-02 18:19 UTC
**Describe the bug**
Generated game scripts do not launch their respective games and thus they don't work on either steam or lutris.

**To Reproduce**
1. Go to "/home/deck/Games/Heroic/HeroicBashLauncher/GameFiles/"
2. Double click a game script for example "NEOTheWorldEndswithYou_Heroic.sh"

**Expected behavior**
The game should launch.

**Game script**
```
#!/bin/bash

    #Generate log
    exec > logs/NEOTheWorldEndswithYou_Heroic.log 2>&1

    #Enable UTF-8 Encoding
    export LC_ALL=en_US.UTF-8

    #Game Name = NEO: The World Ends with You (epic) 

    #App Name = 5ab31c70e0b14ce5bddfd9f9c28f944d

    #Override launch parameters
    /home/deck/Games/Heroic/HeroicBashLauncher/HeroicBashLauncher --update "NEO: The World Ends with You" "5ab31c70e0b14ce5bddfd9f9c28f944d" "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/5ab31c70e0b14ce5bddfd9f9c28f944d.json" "epic"

    

    flatpak run --command=./launchflatpakgame.sh com.heroicgameslauncher.hgl

    #Launch Command
    #/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 5ab31c70e0b14ce5bddfd9f9c28f944d --language es --wine-prefix "/home/deck/Games/Heroic/Prefixes/default/NEO The World Ends with You" --wine /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-12/bin/wine
```
**Log**
```3.32.0
Using Bash Launcher v3.2.4
NOTE - This is an independent project and not affiliated with Heroic Games Launcher.

[cli] INFO: Logging in...
Traceback (most recent call last):
  File "legendary/cli.py", line 3061, in <module>
  File "legendary/cli.py", line 2976, in main
  File "legendary/cli.py", line 592, in launch_game
  File "legendary/core.py", line 187, in login
ValueError: No saved credentials
[4] Failed to execute script 'cli' due to unhandled exception!
wineserver stopped
NEO: The World Ends with You stopped
```
**Details**

 - Platform: Steam Deck
 - OS: Steam OS
 - Heroic Version: v2.9.1 Flatpak
 - Bash Launcher Version: v3.2.4 Flatpak

**Comment by redromnon** [comment] 2023-08-03 01:38
>Traceback (most recent call last):
  File "legendary/cli.py", line 3061, in <module>
  File "legendary/cli.py", line 2976, in main
  File "legendary/cli.py", line 592, in launch_game
  File "legendary/core.py", line 187, in login
ValueError: No saved credentials
[4] Failed to execute script 'cli' due to unhandled exception!

Please check if you've logged in properly in Heroic. This error shows up if haven't logged in.
Also make sure the game launches through Heroic first.

**Comment by redirectto** [comment] 2023-08-03 16:07
Logged in again in various attempts, still the same outcome.
I've tried to close steam, to open steam, to close heroic to open heroic, to recreate the shortcuts and still doesn't work.
My password contains a weird character, maybe that's the reason.

**Comment by redromnon** [comment] 2023-08-05 06:11
I can confirm this is happening to me too. Trying to find a solution for the issue.

**Comment by redromnon** [comment] 2023-08-05 06:14
I can confirm this is happening to me too. Trying to find a solution for the issue. The game launches fine in Heroic but not outside Heroic. 
`legendary` cannot authenticate if run outside Heroic like `/opt/Heroic/resources/app.asar.unpacked/build/bin/lilegendary list`.

**Comment by redromnon** [comment] 2023-08-06 05:39
Let me know if this [build](https://github.com/redromnon/HeroicBashLauncher/actions/runs/5774892249) works

It's not final though, need to make some more fixes. But it should launch games just fine.

**Comment by redirectto** [comment] 2023-08-06 06:06
I have tried 3 games and now they launch properly.
I'll wait for the final build.
Thank you for your time.

**Comment by redromnon** [comment] 2023-08-06 06:09
Feel free to close this issue when I publish the next release.

**Comment by redromnon** [comment] 2023-08-09 02:28
@redirectto Was MangoHUD working for you and displaying the default metrics while playing a game?

**Comment by redromnon** [comment] 2023-08-10 08:43
Yep. There's a checkbox under Settings. Although, I'm not sure if the Steam Deck has a global MangoHud shortcut button.

**Comment by redirectto** [comment] 2023-08-10 20:06
I think it works alright
https://i.imgur.com/p3pUsHl.jpg

**Closed** 2023-08-16 17:12 UTC
Labels: bug
