### ISSUE TITLE
[Bug]Control_Heroic.sh refuses to launch (Steam Deck)

### ISSUE THREAD

**Issue by eddieanthony** [redromnon/HeroicBashLauncher#62] opened 2022-05-15 05:11 UTC
Here is my error message, not sure what the cause is. I only have two epic games installed via Heroic, and the other one (Metro Exodus) is working correctly. Currently running Heroic v2.3.0 and Bash Launcher v2.5.0

> 
> Gtk-Message: 22:05:46.117: Failed to load module "canberra-gtk-module"
> 3.32.0

> Running launch command for Control:
> STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/home/deck/Games/Heroic/Prefixes/Control /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Calluna --no-wine --wrapper "/home/deck/.steam/steam/steamapps/common/Proton 7.0/proton run" 
> [cli] INFO: Logging in...
> [Core] INFO: Trying to re-use existing login session...
> [cli] INFO: Checking for updates...
> [Core] INFO: Getting authentication token...
> [cli] INFO: Launching Calluna...
> Traceback (most recent call last):
>   File "legendary/cli.py", line 3004, in <module>
>   File "legendary/cli.py", line 2919, in main
>   File "legendary/cli.py", line 685, in launch_game
>   File "subprocess.py", line 858, in __init__
>   File "subprocess.py", line 1704, in _execute_child
> FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.steam/steam/steamapps/common/Proton'
> [9] Failed to execute script 'cli' due to unhandled exception!
> ---CANNOT CONNECT TO NETWORK. RUNNING IN OFFLINE MODE---
> [cli] INFO: Launching Calluna...
> Traceback (most recent call last):
>   File "legendary/cli.py", line 3004, in <module>
>   File "legendary/cli.py", line 2919, in main
>   File "legendary/cli.py", line 685, in launch_game
>   File "subprocess.py", line 858, in __init__
>   File "subprocess.py", line 1704, in _execute_child
> FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.steam/steam/steamapps/common/Proton'
> [15] Failed to execute script 'cli' due to unhandled exception!
> Gtk-Message: 22:05:48.153: Failed to load module "canberra-gtk-module"
> 
> ** (zenity:19): WARNING **: 22:05:48.320: AT-SPI: Could not obtain desktop path or name
> 
> 
> ** (zenity:19): WARNING **: 22:05:48.332: AT-SPI: Could not obtain desktop path or name
> 
> 
> ** (zenity:19): WARNING **: 22:05:48.332: atk-bridge: get_device_events_reply: unknown signature
> 
> ** (zenity:19): WARNING **: 22:05:48.332: atk-bridge: get_device_events_reply: unknown signature
> 
> ** (zenity:19): WARNING **: 22:05:48.332: atk-bridge: GetRegisteredEvents returned message with unknown signature
> 
> ** (zenity:19): WARNING **: 22:05:48.343: AT-SPI: Could not obtain desktop path or name
> 
> 
> ** (zenity:19): WARNING **: 22:05:48.343: atk-bridge: get_device_events_reply: unknown signature
> 
> ** (zenity:19): WARNING **: 22:05:48.343: atk-bridge: get_device_events_reply: unknown signature
> 
> ** (zenity:19): WARNING **: 22:05:48.343: atk-bridge: GetRegisteredEvents returned message with unknown signature
> Using Bash Launcher 2.5.0
> 
> Checking if Zenity is installed:

**Comment by redromnon** [comment] 2022-05-15 05:37
Check the pinned #60 issue for the workaround. This is a duplicate of that issue.

**Closed by redromnon** 2022-05-15 05:37 UTC
